### ISSUE TITLE
Catch error if no commits yet

### ISSUE THREAD

**Issue by vweevers** [vweevers/remark-git-contributors#12]

**Comment by wooorm** [comment]
We’re testing this here:

https://github.com/remarkjs/remark-git-contributors/blob/d29f01a03e2fafff52e67b5224469152ea652671/test/index.js#L252-L260

And we’re throwing the error here:

https://github.com/remarkjs/remark-git-contributors/blob/d29f01a03e2fafff52e67b5224469152ea652671/index.js#L49-L51

Now, what’s your reasoning that you think the error should be caught? 

Alternatively, we could warn about no commits as well, like we do with other problems:

https://github.com/remarkjs/remark-git-contributors/blob/d29f01a03e2fafff52e67b5224469152ea652671/index.js#L55

**Comment by vweevers** [comment]
> Now, what’s your reasoning that you think the error should be caught?

It shouldn't be an error when you're creating a new project (and adding remark tooling right from the bat). So we need a distinction between "Could not get git contributors" and "There are no git contributors yet".

> Alternatively, we could warn about no commits as well, like we do with other problems:

I think that makes sense.

None of this is urgent though.
