### ISSUE TITLE
Provide option to filter contributors

### ISSUE THREAD

**Issue by donmahallem** [vweevers/remark-git-contributors#32]
### Initial checklist

- [X] I read the [support docs](https://github.com/remarkjs/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/remarkjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/remarkjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aremarkjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Currently only greenkeeper is statically ignored in the list of contributors but other "popular" Github Bots aren't.

### Solution

As it would be cumbersome to statically programm "every" bot contributor to the source I propose adding a "Default" list of ignored accounts and adding a property/array to the plugin options which describe the ignored accounts.

One option would be to use "simple" descriptors like:
```
{ name?:string,mail?:string}
``` 

### Alternatives

Another option would be to use json-schemas to go the extra mile.

**Comment by wooorm** [comment]
don’t bots nowadays all have a `[bot]` suffix in their username? Could we use that?

**Comment by donmahallem** [comment]
You are right. But for older repos there are still other non `[bot]` bot contributors. For example dependabot. I believe there should still be an option to provide additional exclusions. In general filtering by `[bot]` suffix should be good enough to catch most general cases.

**Comment by wooorm** [comment]
Could there be a case in favor of *including* bots? 🤔

Generally I think you’re right that this is a good addition. Not 100% on how to do it though?

**Comment by donmahallem** [comment]
@wooorm there is.

Options could be
1. Default Bot Block list, which can be overwritten/disabled/expanded
2. No default Block List



In either case there should be a way to specify a regex/match list for relevant properties like username or mail.

Optionally providing filter functions to the plugin isn't encouraged probably?

**Comment by wooorm** [comment]
Released in [5.1.0](https://github.com/remarkjs/remark-git-contributors/releases/tag/5.1.0)!
