### ISSUE TITLE
Support mastodon

### ISSUE THREAD

**Issue by vweevers** [vweevers/remark-git-contributors#4]
@ralphtheninja can you explain how usernames/handles work in mastodon? Do you get a canonical URI? What's the convention for displaying usernames? `domain/@user` or `@user@domain`?

**Comment by ralphtheninja** [comment]
> @ralphtheninja can you explain how usernames/handles work in mastodon? Do you get a canonical URI? What's the convention for displaying usernames? domain/@user or @user@domain?

Sure.

So if we take a look at my profile here: https://social.weho.st/@ralph

The convention of displaying usernames is `@user@domain`, so in my case that would be `@ralph@social.weho.st` and the URI to a profile is `http{s}://domain/@user`

**Comment by vweevers** [comment]
Thanks. Does it make sense to extend that convention to twitter? We could add a `Social` header to the table, and the values would be `@ralph@social.weho.st` or `@vweevers@twitter`.

**Comment by vweevers** [comment]
Sorry for mentioning you, @user 😄

**Comment by ralphtheninja** [comment]
> Thanks. Does it make sense to extend that convention to twitter? We could add a Social header to the table, and the values would be @ralph@social.weho.st or @vweevers@twitter.

That would be really nice I think.

**Comment by vweevers** [comment]
Options:

1. Add a feature to `remark-contributors` to parse a `social` property as a twitter or mastodon handle. I don't like this because it means metadata (in `package.json` or modules like `level-community`) has to change (with loss of information).
2. Add a feature to `remark-contributors` to use a `Social` header instead of `Twitter` if a `mastodon` property is found in any of the contributors.
3. Add a feature to `remark-contributors` to accept custom formatting options. Something like:

```js
headers: {
 social: {
   name: 'Social',
   value: function (value, contributor) {
     if (contributor.twitter) return twitterLink(contributor.twitter)
     // ..
   }
 }
}
```

4. Add a feature to `remark-contributors` to accept raw markdown or mdast nodes (so that we can pass in links). This is the easiest solution atm.
5. Fork.

**Comment by ralphtheninja** [comment]
With the things happening at GitHub and Microsoft etc should we go even further with this and allow for other Git*-accounts? Perhaps for a later discussion, but just wanted to mention it here since we're already pondering the `Social` header instead of _just_ Twitter.

**Comment by ralphtheninja** [comment]
3. sounds like a good option to me. Maybe we can use this same approach for other Git*-accounts?

**Comment by vweevers** [comment]
Problem with other git* is the lack of discoverable HTTP API's and that we need some unique property to match profiles to metadata. Right now that's the `github` property.

It might be easier to use `git` users after all, and match by `email`. We would need to add past and present email addresses to `level-community`.

Hmm, in things like `git-ssb`, do users have an email address?

**Comment by vweevers** [comment]
(Side note: I'm in the "happy with microsoft" camp but also interested in decentralized githubs)

**Comment by ralphtheninja** [comment]
> (Side note: I'm in the "happy with microsoft" camp but also interested in decentralized githubs)

I think we're on the same page.

> Hmm, in things like git-ssb, do users have an email address?

I don't believe so.

cc @ansuz

**Comment by vweevers** [comment]
https://github.com/hughsk/remark-contributors/pull/7

**Comment by vweevers** [comment]
Yeah, `git-ssb` users are identified by their scuttlebot id:

```
git-ssb-web (master) (git-ssb-web@2.11.1)
$ git log -n 1
commit b0b0e18c718add6a6fa1eb7b60d367ea91e01f54 (HEAD -> master, tag: v2.11.1, origin/master, origin/HEAD)
Author: cel <cel@f/6sQ6d2CMxRUhLpspgGIulDxDCwYD7DzFzPNr7u5AU=.ed25519>
Date:   Mon Jun 4 23:12:33 2018 -0400

    2.11.1
```

*Edit: wait, that kinda looks like an email address though*

**Comment by vweevers** [comment]
So, correction, it works just like regular git, with email addresses stored in git objects.

**Comment by vweevers** [comment]
Mastodon is now supported. See #6 for continued discussion on github alternatives.
