### ISSUE TITLE
Support GitHub alternatives (as profile)

### ISSUE THREAD

**Issue by vweevers** [vweevers/remark-git-contributors#6]
Replace the `GitHub` header with a `Profile` header (suggestions welcome). Values would be e.g.:

- `[**@user**](https://github.com/user)` 
- `[**@user**](https://bitbucket.com/user)` (etc for GitLab, ..)

This doesn't work with `git-ssb` since there is no central hub, but perhaps we can just display a scuttlebot id without a link (if set in metadata).

For a list of GitHub alternatives, see https://docs.google.com/spreadsheets/d/1LZryaOx4VYHQ_oWLtRjvFrr4RhVjR484eFe7du3Usa4/edit#gid=0

**Comment by wooorm** [comment]
I think it’s fine to support the big ones: GitLab (`https://gitlab.com/staltz`) and Bitbucket (`https://bitbucket.org/wooorm/`).
For git-ssb, do you have an example of a link / URL / ID that people are using in the wild?

There’s quite some code for GH:

https://github.com/remarkjs/remark-git-contributors/blob/d29f01a03e2fafff52e67b5224469152ea652671/index.js#L62-L72

Mainly, we need to figure out if GitLab and Bitbucket also support bots and hiding emails, and which formats they use for them. Any ideas on this?

**Comment by wooorm** [comment]
Seems like Bitbucket and GitLab don’t support hiding emails (like GH does with its noreply), nor do they allow specific bot accounts (GHs `[bot]` suffix)

**Comment by vweevers** [comment]
> For git-ssb, do you have an example of a link / URL / ID that people are using in the wild?

In git it looks like:

```
git-ssb-web (master) (git-ssb-web@2.11.1)
$ git log -n 1
commit b0b0e18c718add6a6fa1eb7b60d367ea91e01f54 (HEAD -> master, tag: v2.11.1, origin/master, origin/HEAD)
Author: cel <cel@f/6sQ6d2CMxRUhLpspgGIulDxDCwYD7DzFzPNr7u5AU=.ed25519>
Date:   Mon Jun 4 23:12:33 2018 -0400

    2.11.1
```

Here's an example of such an ID in markdown:

https://github.com/deltachat/deltachat-desktop/blob/3ba4621cddd344ff8bb018446097f3c62095e0b5/AUTHORS.md

**Comment by vweevers** [comment]
cc @ralphtheninja (what do you need for deltachat?)

**Comment by ralphtheninja** [comment]
I guess it would be nice if this table (generated by `hallmark`) would be more complete https://github.com/deltachat/deltachat-desktop/blob/master/CONTRIBUTORS.md , but not sure how this can be done.

**Comment by wooorm** [comment]
Hmm, but deltachat-desktop doesn’t have any `'contributors'` configured, right? So we can’t find names beloning to emails.

So I’m thinking remark-git-contributors sees the two noreply emails and infers the corresponding usernames for those.

Now, bitbucket and gitlab don’t support this feature, and GH only if noreply’s are used, but I guess it could work for ssb: `cel@f/6sQ6d2CMxRUhLpspgGIulDxDCwYD7DzFzPNr7u5AU=.ed25519` and `substack@9nTgtYmvW4HID6ayt6Icwc8WZxdifx5SlSKKIX/X/1g=.ed25519` have a username.

For ssb IDs, how should we link to them?

**Comment by vweevers** [comment]
> So I’m thinking remark-git-contributors sees the two noreply emails and infers the corresponding usernames for those.

Yup. It wasn't designed to do that 😄 

> For ssb IDs, how should we link to them?

In Scuttlebutt clients like Patchwork, links look like this:

```
[substack](@9nTgtYmvW4HID6ayt6Icwc8WZxdifx5SlSKKIX/X/1g=.ed25519)
```

To put that into words, the ID _is_ the canonical URL. Such links don't work outside of Scuttlebutt and there's no central HTTP server to link to (apart from a few volunteer-run instances of [`ssb-viewer`](https://github.com/ssbc/ssb-viewer) like [viewer.scuttlebot.io](https://viewer.scuttlebot.io/)). And Scuttlebutt has no global store of identities or names.

Maybe we can use `ssb://`, which is a [whitelisted protocol handler for WebExtensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/protocol_handlers) and could become more commonplace in the future. E.g.:

```
[`substack@9nTgtYmvW4HID6ayt6Icwc8WZxdifx5SlSKKIX/X/1g=.ed25519`](ssb://@9nTgtYmvW4HID6ayt6Icwc8WZxdifx5SlSKKIX/X/1g=.ed25519)
```

That at least gives _some_ users _some_ way of following the link.

**Comment by wooorm** [comment]
Revisiting this, I’m not sure this should be done in this project, because I don’t think there’s a right way. Take these cases:

- A project was first hosted on GitHub, with GitHub users carefully collected, and has now move to GitLab. Not all the people with a  `github` handle have the same name / a profile on GitLab.
- A project is hosted in several places, GitLab and GitHub.

**Solution**:

- One column for each network, so one for GH and one for GL.
- One column for all networks. But in which order? Is GH preferred? Something else?

These cases may be handled by formatters... We could pass custom formatters through to [`remark-contributors`](https://github.com/remarkjs/remark-contributors)?

**Comment by vweevers** [comment]
@wooorm I agree there's no right way, at least automatically. So I suggest that we require users to use [metadata](https://github.com/remarkjs/remark-git-contributors#metadata) for cases like these. E.g:

```json
{
    "name": "André Staltz",
    "email": [
      "andre-example@gmail.com",
      "staltz@some-long-ssb-id"
    ],
    "gitlab": "staltz"
}
```

`remark-git-contributors` could then match git users by email (even when they used different email addresses at times) and use the first property it finds (github, gitlab, bitbucket) for a "Profile" column. Formatted accordingly. This means each developer can choose their preferred profile / network.

But to be honest, I prefer just closing this issue until someone really wants it and has a well-defined use case and desired outcome.

**Comment by wooorm** [comment]
#### Profile vendors

Right, we can’t really infer usernames (except on GH, through noreply emails). *Except* if they are provided through metadata (or with noreply’s in case of GitHub).

Say we have the following metadata:

```js
{name: "Anna", github: "anna"},
{name: "Bisma", github: "bisma94", gitlab: "bisma"},
{name: "Chun", gitlab: "chunchun", bitbucket: "chun"}
```

You are proposing to pick the first key. We can do that by looping through a user, and picking the first of `github`, `gitlab`, `bitbucket`, or `scuttlebutt` / `ssb`. The logical way to do that though is by looping through all users, who may be sorted from first-contributed to last, which may not be great in case 1 I mentioned before if the project moved to gitlab, and they’d prefer gitlab profiles, but the first user is no longer active.
We can also allow people to specify a preference array (such as `['gitlab', 'bitbucket']`, which has the benefit of being able to ignore profiles from a specific vendor).
In the future, we could allow people to add custom profiles, and this array could then be expanded to a config object similar to formatters.

I suggest:
- `ssb` keys, mapping to `[**@substack**](ssb://@9nTgtYmvW4HID6ayt6Icwc8WZxdifx5SlSKKIX/X/1g=.ed25519)`
- Adding titles to users: `[**@wooorm**](https://github.com/wooorm "View @wooorm on GitHub")`
- Preference array, with a default of `['github', 'gitlab', 'bitbucket', 'ssb']`
- Supporting those four “out of the box”, not allowing others (’till someone requests it)

#### Emails

Hmm, that’s what `.mailmap` already does. I lightly vote to not duplicate email handling if it’s already in Git: letting Git pull that weight.

**Comment by vweevers** [comment]
> You are proposing to pick the first key.

Not exactly. What I meant to say was: a user should only have one key; we'll ignore additional keys.

> Hmm, that’s what .mailmap already does. I lightly vote to not duplicate email handling if it’s already in Git: letting Git pull that weight.

It's already supported:

https://github.com/remarkjs/remark-git-contributors/blob/c1640608d2f8817358d34aabb7e93275caf11933/index.js#L244-L248

The benefit of this over `.mailmap` is you can reuse the metadata across modules, by putting the metadata itself in an npm package.

**Comment by wooorm** [comment]
> Not exactly. What I meant to say was: a user should only have one key; we'll ignore additional keys.

Ahh.. OK, that makes sense. To have people pick their own preferred platform.
I still kinda dislike `for (key in value)` because it’s not guaranteed to work, although it always does.

Other idea: We could do what you suggest, but document a `preferred: $profileName` key, where each person can have 0 or more profiles, specified in any order, but pick which they prefer.

So that:

```js
{name: "Anna", github: "anna"},
{name: "Bisma", github: "bisma94", gitlab: "bisma"},
{name: "Chun", gitlab: "chunchun", bitbucket: "chun", preferred: "bitbucket"}
```

Anna gets a GH link, Bisma a GH link (because that’s the first profile key), and Chun a BB link because that’s preferred?

> It's already supported:

Oh I forgot lol. Well in that case we’re fine 😊

**Comment by vweevers** [comment]
SGTM. I like the `preferred` solution more than the preference array, because it doesn't change the shape of the object. I'm not convinced we really need this feature but it's small, so 👍

**Comment by wooorm** [comment]
> But to be honest, I prefer just closing this issue until someone really wants it and has a well-defined use case and desired outcome.

Lol I missed this. I agree. I’m going to do that now

I started thinking about how to implement this, and [`remarkjs/remark-contributors`](https://github.com/remarkjs/remark-contributors) is really made to map one property to a cell. Not to map several properties into one cell.

Anyway, it’s doable, but adds some logic, and isn’t trivial. So yeah, if someone needs it we can re-open.
